# Generated by Django 5.1.3 on 2024-12-25 07:44

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("profile_url", models.CharField(max_length=255)),
                (
                    "settings",
                    models.TextField(
                        default='{"city": "Beograd", "price": "50000-150000", "size": "45-120", "rooms": "3.0"}'
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
