# Generated by Django 5.1.3 on 2025-01-02 13:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0003_user_chat_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="profile_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="settings",
            field=models.TextField(
                default='{"city": "Beograd", "price": "50000-150000", "size": "45-120", "rooms": "3.0", "is_enabled": true}'
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
