# Generated by Django 5.1.3 on 2024-12-17 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Listing",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("source_id", models.CharField(max_length=255)),
                ("url", models.CharField(unique=True)),
                ("title", models.CharField(max_length=255)),
                ("short_description", models.TextField(null=True)),
                ("detail_description", models.TextField(null=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("price_currency", models.CharField(max_length=3)),
                ("status", models.CharField(max_length=255)),
                ("first_seen_at", models.DateTimeField()),
                ("last_seen_at", models.DateTimeField()),
                ("valid_from", models.DateTimeField()),
                ("valid_to", models.DateTimeField()),
                ("total_views", models.IntegerField()),
                ("city", models.CharField(max_length=255)),
                ("municipality", models.CharField(max_length=255)),
                ("micro_location", models.CharField(max_length=255)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField()),
                ("total_pages", models.IntegerField()),
                ("total_listings", models.IntegerField()),
                ("item_scraped_count", models.IntegerField()),
                ("item_dropped_count", models.IntegerField()),
                ("item_error_count", models.IntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Source",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("base_url", models.CharField(max_length=255, unique=True)),
                ("scraper_config", models.TextField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("source_url", models.CharField(default="")),
                ("url", models.CharField(default="")),
                ("sequence_number", models.IntegerField()),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="listings.listing",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Property",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("property_type", models.CharField(max_length=255)),
                ("building_type", models.CharField(max_length=255, null=True)),
                ("size_m2", models.FloatField()),
                ("floor_number", models.IntegerField(null=True)),
                ("total_floors", models.IntegerField(null=True)),
                ("rooms", models.FloatField(null=True)),
                ("property_state", models.CharField(max_length=255, null=True)),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="listings.listing",
                    ),
                ),
            ],
            options={
                "verbose_name": "Property",
                "verbose_name_plural": "Properties",
            },
        ),
        migrations.CreateModel(
            name="RawData",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("html", models.TextField()),
                ("data", models.TextField()),
                (
                    "listing",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="listings.listing",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ListingChange",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("change_type", models.CharField(max_length=255)),
                ("field", models.CharField(max_length=255)),
                ("old_value", models.TextField(null=True)),
                ("new_value", models.TextField(null=True)),
                ("changed_at", models.DateTimeField()),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="listings.listing",
                    ),
                ),
                (
                    "raw_data",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="listings.rawdata",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Seller",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("source_seller_id", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("seller_type", models.CharField(max_length=255)),
                ("primary_phone", models.CharField(max_length=255, null=True)),
                ("primary_email", models.CharField(max_length=255, null=True)),
                ("website", models.CharField(max_length=255, null=True)),
                (
                    "source",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="listings.source",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
