# Generated by Django 5.1.3 on 2024-12-01 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="rawdata",
            name="listing_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="listings.listing",
            ),
        ),
        migrations.AddField(
            model_name="rawdata",
            name="reponse_time",
            field=models.FloatField(null=True),
        ),
    ]
