# Generated by Django 5.1.3 on 2024-12-01 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0002_rawdata_listing_id_rawdata_reponse_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="listing",
            name="description",
        ),
        migrations.AddField(
            model_name="listing",
            name="detail_description",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="listing",
            name="short_description",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="listingchange",
            name="raw_data_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="listings.rawdata",
            ),
        ),
    ]
