# Generated by Django 5.1.3 on 2024-12-18 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "listings",
            "0003_rename_item_error_count_report_response_error_count_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Error",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("error_type", models.CharField(max_length=255)),
                ("error_message", models.TextField()),
                ("error_traceback", models.TextField()),
                (
                    "source",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="listings.source",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
