# Generated by Django 5.1.3 on 2024-12-02 04:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0003_remove_listing_description_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="image",
            old_name="listing_id",
            new_name="listing",
        ),
        migrations.RenameField(
            model_name="listingchange",
            old_name="listing_id",
            new_name="listing",
        ),
        migrations.RenameField(
            model_name="listingchange",
            old_name="raw_data_id",
            new_name="raw_data",
        ),
        migrations.RenameField(
            model_name="property",
            old_name="listing_id",
            new_name="listing",
        ),
        migrations.RenameField(
            model_name="rawdata",
            old_name="listing_id",
            new_name="listing",
        ),
        migrations.RenameField(
            model_name="seller",
            old_name="source_id",
            new_name="source",
        ),
    ]
