# Generated by Django 5.1.3 on 2024-12-02 04:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0004_rename_listing_id_image_listing_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="rooms",
            field=models.FloatField(),
        ),
    ]
