# Generated by Django 5.1.3 on 2024-12-18 14:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0004_error"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="error",
            name="source",
        ),
        migrations.AddField(
            model_name="error",
            name="url",
            field=models.CharField(default="", max_length=255),
        ),
    ]
