# Generated by Django 5.1.3 on 2024-12-02 05:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0005_alter_property_rooms"),
    ]

    operations = [
        migrations.RenameField(
            model_name="seller",
            old_name="seller_id",
            new_name="source_seller_id",
        ),
        migrations.AlterField(
            model_name="source",
            name="base_url",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
