# Generated by Django 5.1.3 on 2024-12-18 14:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0005_remove_error_source_error_url"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="image",
            constraint=models.UniqueConstraint(
                fields=("url", "listing"), name="unique_url_listing"
            ),
        ),
    ]
