# Generated by Django 5.1.3 on 2024-12-02 05:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0006_rename_seller_id_seller_source_seller_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seller",
            name="primary_email",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="seller",
            name="primary_phone",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
