# Generated by Django 5.1.3 on 2024-12-18 15:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0007_error_unique_error_constraint"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="valid_from",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="listing",
            name="valid_to",
            field=models.DateTimeField(null=True),
        ),
    ]
