# Generated by Django 5.1.3 on 2024-12-04 15:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0008_alter_seller_website"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="property_state",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
