# Generated by Django 5.1.3 on 2024-12-24 09:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0008_alter_listing_valid_from_alter_listing_valid_to"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="city",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="listing",
            name="latitude",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="listing",
            name="longitude",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="listing",
            name="micro_location",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="listing",
            name="municipality",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="listing",
            name="total_views",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="property",
            name="floor_number",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="property",
            name="property_type",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
