# Generated by Django 5.1.3 on 2024-12-04 17:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0009_alter_property_property_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listingchange",
            name="new_value",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="listingchange",
            name="old_value",
            field=models.TextField(null=True),
        ),
    ]
