# Generated by Django 5.1.3 on 2024-12-24 09:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0009_alter_listing_city_alter_listing_latitude_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="source_name",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
