# Generated by Django 5.1.3 on 2024-12-04 17:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0010_alter_listingchange_new_value_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="floor_number",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="property",
            name="rooms",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="property",
            name="total_floors",
            field=models.IntegerField(null=True),
        ),
    ]
