# Generated by Django 5.1.3 on 2024-12-04 17:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0011_alter_property_floor_number_alter_property_rooms_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="building_type",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
