# Generated by Django 5.1.3 on 2024-12-27 23:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0003_user_chat_id"),
        ("listings", "0012_queue"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="queue",
            constraint=models.UniqueConstraint(
                fields=("listing", "user"), name="unique_listing_and_user_queue"
            ),
        ),
    ]
