# Generated by Django 5.1.3 on 2024-12-08 15:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0012_alter_property_building_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="size_m2",
            field=models.FloatField(),
        ),
    ]
