# Generated by Django 5.1.3 on 2024-12-30 09:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0013_queue_unique_listing_and_user_queue"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="total_actual_listings",
            field=models.IntegerField(default=0),
        ),
    ]
