# Generated by Django 5.1.3 on 2025-01-03 22:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0014_report_total_actual_listings"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="total_changed_listings",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="report",
            name="total_new_listings",
            field=models.IntegerField(default=0),
        ),
    ]
