# Generated by Django 5.1.3 on 2025-01-04 13:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0015_report_total_changed_listings_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="property",
            constraint=models.UniqueConstraint(
                fields=(
                    "property_type",
                    "building_type",
                    "size_m2",
                    "floor_number",
                    "total_floors",
                    "rooms",
                    "property_state",
                ),
                name="unique_property_constraint",
            ),
        ),
    ]
