# Generated by Django 5.1.3 on 2025-01-08 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0016_property_unique_property_constraint"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="listing",
            name="source_id",
        ),
        migrations.AddField(
            model_name="listing",
            name="source",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="listings.source",
            ),
        ),
    ]
