# Generated by Django 5.1.3 on 2025-01-16 00:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0019_agent_alter_property_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="size_m2",
            field=models.FloatField(null=True),
        ),
    ]
