# Generated by Django 5.1.3 on 2025-01-29 06:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0021_alter_agent_registry_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="listing",
            name="total_views",
        ),
        migrations.RemoveField(
            model_name="listing",
            name="valid_from",
        ),
        migrations.RemoveField(
            model_name="listing",
            name="valid_to",
        ),
    ]
