listing_insert_query = """
INSERT INTO listings_listing (
    id,
    created_at,
    updated_at,
    first_seen_at,
    last_seen_at,
    source_id,
    url,
    title,
    short_description,
    detail_description,
    price,
    price_currency,
    status,
    valid_from,
    valid_to,
    total_views,
    city,
    municipality,
    micro_location,
    latitude,
    longitude
) VALUES (
    %(listing_id)s,
    now(),
    now(),
    now(),
    now(),
    %(source_id)s,
    %(url)s,
    %(title)s,
    %(short_description)s,
    %(detail_description)s,
    %(price)s,
    %(price_currency)s,
    %(status)s,
    %(valid_from)s,
    %(valid_to)s,
    %(total_views)s,
    %(city)s,
    %(municipality)s,
    %(micro_location)s,
    %(latitude)s,
    %(longitude)s
) ON CONFLICT (url) DO UPDATE SET last_seen_at = now();
"""
